  server:
    port: 8081 # ??(?) ?? (?????? 8080? ? ?? ?? ???)

  spring:
    application:
      name: ticket-server

    # 1. ?????? ?? (Docker Compose? ???? ?)
    datasource:
      url: jdbc:mariadb://localhost:3306/ticket_db
      username: user
      password: 1234
      driver-class-name: org.mariadb.jdbc.Driver

    # 2. JPA (ORM) ??
    jpa:
      hibernate:
        ddl-auto: create  # ?? ?? ? Entity ?? ??? ?? ?? (???? validate ??)
      show-sql: true      # ???? SQL ??? ??? ???
      properties:
        hibernate:
          format_sql: true # SQL? ?? ?? ??? ??
      open-in-view: false  # OSIV ?? (DB ???? ?? ???? ?? ???)

    # 3. Redis ?? (Docker Compose? ???? ?)
    data:
      redis:
        host: 0.0.0.0
        port: 6379
        password: 1234 # ???? ??? ????

    # 4. [???] Java 21/25 ?? ??? ??? (??? ??? ???)
    threads:
      virtual:
        enabled: true

  # 5. gRPC ?? ??
  grpc:
    server:
      port: 9090             # ?????? ??? ??? (static://localhost:9090)
      negotiation-type: PLAINTEXT # ?????? SSL ?? ?? ??

  # 6. ?? ?? ??
  logging:
    level:
      root: INFO
      com.hunecion.portfolio: DEBUG # ?? ??? ???? ??
      org.hibernate.SQL: DEBUG      # ?? ???? ??