server:
  port: 8081

spring:
  application:
    name: ticket-server

  # 1. Database
  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:3306/ticket_db?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  # 2. JPA (ORM)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  # 3. Redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

  # 4. Virtual Threads (Java 21+)
  threads:
    virtual:
      enabled: true

# 5. gRPC Configuration
grpc:
  server:
    port: 9090
    negotiation-type: PLAINTEXT

# 6. Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    metadata-map:
      gRPC.port: ${grpc.server.port}

# 7. Logging Configuration
logging:
  level:
    root: INFO
    com.server.portfolio: DEBUG
    org.hibernate.SQL: DEBUG