  server:
    port: 8081

  spring:
    application:
      name: ticket-server

    # 1. Database
    datasource:
      url: jdbc:mariadb://${DB_HOST:localhost}:3306/ticket_db?createDatabaseIfNotExist=true
      username: root
      password: 1234
      driver-class-name: org.mariadb.jdbc.Driver

    # 2. JPA (ORM)
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
      open-in-view: false

    # 3. Redis
    data:
      redis:
        host: ${REDIS_HOST:localhost}
        port: 6379
        password: 1234

    # 4. [???] Java 21/25 ?? ??? ??? (??? ??? ???)
    threads:
      virtual:
        enabled: true

  # 5. gRPC ?? ??
  grpc:
    server:
      port: 9090             # ?????? ??? ??? (static://localhost:9090)
      negotiation-type: PLAINTEXT # ?????? SSL ?? ?? ??

  # 6. ?? ?? ??
  logging:
    level:
      root: INFO
      com.server.portfolio: DEBUG # ?? ??? ???? ??
      org.hibernate.SQL: DEBUG      # ?? ???? ??