server:
  port: 8083

grpc:
  client:
    ticket-server:
      address: static://localhost:9090
      negotiation-type: plaintext
    payment-service:
      address: static://localhost:9092
      negotiation-type: plaintext

jwt:
  secret: vmfhaltmskdlstkfkdgodyrjsmsepsoftjqtrmthansdurskdlrjqtlsdlqslekdksgrkdhkfy