server:
  port: 8083

grpc:
  client:
    ticket-server:
      address: static://${TICKET_SERVER_HOST:localhost}:9090
      negotiation-type: plaintext
    payment-service:
      address: static://${PAYMENT_SERVICE_HOST:localhost}:9091
      negotiation-type: plaintext

jwt:
  secret: vmfhaltmskdlstkfkdgodyrjsmsepsoftjqtrmthansdurskdlrjqtlsdlqslekdksgrkdhkfy