server:
  port: 8080 # ?????? 8080 ?? ?? (??? 9090 ?? ?)

grpc:
  client:
    ticket-server: # ? ???? ?? ?? ?? (???? ? ??? ?)
      address: static://localhost:9090 # ??? ?? ?? (?? ?? ?? 9090)
      negotiation-type: plaintext # ?????? SSL ?? ??