server:
  port: 8083 # Changed from 8080 to avoid conflicts

grpc:
  client:
    ticket-server: # ? ???? ?? ?? ?? (???? ? ??? ?)
      address: static://localhost:9090 # ??? ?? ?? (?? ?? ?? 9090)
      negotiation-type: plaintext # ?????? SSL ?? ??